# Generated by Django 5.2.4 on 2025-08-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.URLField(max_length=500)),
                ('Name', models.CharField(max_length=200)),
                ('Brand', models.CharField(max_length=200)),
                ('Mileage', models.FloatField()),
                ('TopSpeed', models.FloatField()),
            ],
        ),
    ]
